[package]
name = "db_lab_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3"
eframe = "0.19.0"
egui_extras = "0.19.0"
colored = "2.0.0"
chrono = "0.4.22"
